name: checkthelists
description: Awesome Checklists for Everything
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.4
  flutter_svg: ^0.17.4
  mobx: ^1.1.1
  mobx_codegen: ^1.0.3
  provider: ^4.0.4
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.8.1

flutter_icons:
 image_path: "images/CheckTheListsIcon.png"
 android: true
 ios: true


flutter:
  uses-material-design: true

  assets:
   - images/Logo.svg
   - images/LogoDark.svg

  fonts:
    - family: ProFont For Powerline
      fonts:
        - asset: fonts/ProFont_For_Powerline.ttf
        - asset: fonts/ProFont_Bold_For_Powerline.ttf
          weight: 700
